name: flutter_tutorials
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.20.0
  firebase_storage: ^11.2.5
  get: ^4.6.5
  google_sign_in: ^6.1.4
  transparent_image: ^2.0.1
  flutter:
    sdk: flutter
  firebase_auth: ^4.12.0
  intl: ^0.18.1
  image_cropper: ^5.0.0
  cloud_firestore: ^4.12.1
  cached_network_image: ^3.3.0
  image_picker: 
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
