// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSpaqJ74bL_I7g_9Vc5CiKtZEZIM5weM',
    appId: '1:59477274670:web:88d0c8c2478cecbbe36fbf',
    messagingSenderId: '59477274670',
    projectId: 'fluttertutorials-24ff7',
    authDomain: 'fluttertutorials-24ff7.firebaseapp.com',
    storageBucket: 'fluttertutorials-24ff7.appspot.com',
    measurementId: 'G-7VSJG2D665',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnke8epgdz1X091KEAnHo5z7kV4qvMZiU',
    appId: '1:59477274670:android:6dabb3e65ac42802e36fbf',
    messagingSenderId: '59477274670',
    projectId: 'fluttertutorials-24ff7',
    storageBucket: 'fluttertutorials-24ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCXFM1j4KALJlPjVyzsN134UMMzRFSRwE',
    appId: '1:59477274670:ios:48d1fba4d8afcc1ae36fbf',
    messagingSenderId: '59477274670',
    projectId: 'fluttertutorials-24ff7',
    storageBucket: 'fluttertutorials-24ff7.appspot.com',
    iosBundleId: 'com.example.flutterTutorials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCXFM1j4KALJlPjVyzsN134UMMzRFSRwE',
    appId: '1:59477274670:ios:091831c3a98b882ee36fbf',
    messagingSenderId: '59477274670',
    projectId: 'fluttertutorials-24ff7',
    storageBucket: 'fluttertutorials-24ff7.appspot.com',
    iosBundleId: 'com.example.flutterTutorials.RunnerTests',
  );
}
